### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by devilflippy** [guillaumearm/SPT_The_Escape#101]
[Practical Tactical 1.4](https://hub.sp-tarkov.com/files/file/2242-practical-tactical/)
[UI Fixes 2.4.2](https://hub.sp-tarkov.com/files/file/1860-ui-fixes/)
[War Heads 1.0.5](https://hub.sp-tarkov.com/files/file/1796-war-heads/)
[Corter Modsync 0.8.0](https://github.com/c-orter/modsync/releases/tag/v0.8.2)

**Comment by guillaumearm** [comment]
done
