### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by devilflippy** [guillaumearm/SPT_The_Escape#107]
[Borkel's Realistic Night Vision Goggles](https://hub.sp-tarkov.com/files/file/1303-borkel-s-realistic-night-vision-goggles-nvgs-and-t-7/#versions) package still 1.0.1, so hard to tell if it's updated
[Skills Extended 1.3.0](https://hub.sp-tarkov.com/files/file/1722-skills-extended/#versions) package.json outdated
[Headshot Darkness 1.1.0](https://hub.sp-tarkov.com/files/file/2164-headshot-darkness/)
[Interactable Exfils API 1.1.0](https://hub.sp-tarkov.com/files/file/2286-interactable-exfils-api/)

**Comment by guillaumearm** [comment]
- Borkel didn't bump the version in his package.json but we have the correct version
- For SkillsExtended I updated the package.json and pushed the change on `master` branch ✅ 
- Headshot darkness has already been updated ✅ 
- Interactable Exfils API: I don't have installed yet so no need to upgrade (I need to take some time to test it before adding it)
