### ISSUE TITLE
Cleanup devilflippy's embedded mods

### ISSUE THREAD

**Issue by guillaumearm** [guillaumearm/SPT_The_Escape#66]
Prefer to release a zip on the concerned repository and add a direct link in the README.md to this zip.

Only the config should stay in `The_Escape` repository (for easier maintainance)

**Comment by devilflippy** [comment]
[Better sales to Traders](https://github.com/devilflippy/Better_sales_to_Traders)
[Tarkov Insurance&Repair Services](https://github.com/devilflippy/Tarkov_Insurance-Repair_Services)
